# This is a basic workflow to help you get started with Actions 

name: CI     

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch 
on:    
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: Create directory path
        run: mkdir -p ./buildOutput

      - name: Generate SBOM using Microsoft sbom-tool
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b ./buildOutput -bc . -pn Test -pv 1.0.0 -ps Adrian_Diglio -nsb http://sysinternals/ -v Verbose
          ls ./buildOutput/_manifest/spdx_2.2/
          cat ./buildOutput/_manifest/spdx_2.2/manifest.spdx.json
      # Runs a single command using the runners shell
      - name: CycloneDX Python Generate SBOM
       # You may pin to the exact commit or the version.
       # uses: CycloneDX/gh-python-generate-sbom@39fe80937489538e12de5a7b427e078649ec44bb
        uses: CycloneDX/gh-python-generate-sbom@v2.0.0
        with:
          # The path to a pip requirements file
          input: "./requirements.txt"
           # Output filename
          output: "./bom.xml" # optional, default is ./bom.xml
          # Output format
          format: xml # optional, default is xml
          
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.2.0
        with: 
          # Path to the artifact serving as the subject of the attestation. Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums". May contain a glob pattern or list of paths (total subject count cannot exceed 1024).
          subject-path: ./buildOutput
          # Digest of the subject for which provenance will be generated. Must be in the form "algorithm:hex_digest" (e.g. "sha256:abc123..."). Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums".
          subject-digest: ${{ env.steps.build-and-push.outputs.digest }}
          # Subject name as it should appear in the attestation. Required when identifying the subject with the "subject-digest" input.
          subject-name: Demo-for-Microsoft-SBOM-Tool
          # Path to checksums file containing digest and name of subjects for attestation. Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums".
          subject-checksums: ./buildOutput
          # Whether to push the provenance statement to the image registry. Requires that the "subject-name" parameter specify the fully-qualified image name and that the "subject-digest" parameter be specified. Defaults to false.
          show-summary: true
           
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0 
        with:
          path: buildOutput
